replicaCount: 2

image:
  repository: 654654364687.dkr.ecr.us-east-1.amazonaws.com/hookdrop
  tag: "latest"
  pullPolicy: Always

imagePullSecrets:
  - name: ecr-secret

ingress:
  enabled: true
  className: nginx
  host: hookdrop.yourdomain.com

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 256Mi

env:
  OTEL_SERVICE_NAME: "hookdrop"
  OTEL_EXPORTER_OTLP_ENDPOINT: "otel-collector.observability.svc.cluster.local:4317"

serviceAccount:
  automountServiceAccountToken: false

monitoring:
  serviceMonitor:
    enabled: true
    interval: 15s
  prometheusRule:
    enabled: true
    errorRateThreshold: 0.05

networkPolicy:
  enabled: true
