replicaCount: 2

image:
  repository: 654654364687.dkr.ecr.us-east-1.amazonaws.com/hookdrop
  tag: "latest"
  pullPolicy: Always

imagePullSecrets:
  - name: ecr-secret

ingress:
  enabled: true
  className: nginx
  host: hookdrop.yourdomain.com

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 256Mi
