replicaCount: 1

image:
  repository: 654654364687.dkr.ecr.us-east-1.amazonaws.com/hookdrop
  tag: "sha-317f6abf9b99bc2bbb3bfc4bfffe1dad869b114f"
  pullPolicy: IfNotPresent

imagePullSecrets:
  - name: ecr-key

ecrRefresher:
  enabled: true
  schedule: "0 */8 * * *"
  region: "us-east-1"
  registry: "654654364687.dkr.ecr.us-east-1.amazonaws.com"
  secretName: "ecr-key"
  awsCredentialsSecret: "aws-credentials"

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

ingress:
  enabled: false
  className: ""
  host: hookdrop.local

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 128Mi

hpa:
  enabled: true
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 70

env:
  PORT: "8080"
  LOG_LEVEL: "info"
  OTEL_SERVICE_NAME: "hookdrop"
  OTEL_EXPORTER_OTLP_ENDPOINT: "otel-collector.observability.svc.cluster.local:4317"

serviceAccount:
  create: true
  name: ""
  annotations: {}
  automountServiceAccountToken: false

monitoring:
  serviceMonitor:
    enabled: false
    interval: 15s
  prometheusRule:
    enabled: false
    errorRateThreshold: 0.05

networkPolicy:
  enabled: true
