apiVersion: pipelinesascode.tekton.dev/v1alpha1
kind: Repository

metadata:
  name: hookdrop-repo
  namespace: hookdrop-ci

spec:
  url: https://github.com/nirjxr26/HookDrop
  git_provider:
    type: github
    secret:
      name: github-token-secret
      key: provider.token