apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  generateName: hookdrop-release-
  namespace: hookdrop-ci
spec:
  taskRunTemplate:
    serviceAccountName: tekton-hookdrop
  pipelineRef:
    name: hookdrop-release
  params:
    - name: repo-url
      value: https://github.com/nirjxr26/HookDrop.git
    - name: revision
      value: main
    - name: aws-region
      value: us-east-1
    - name: image-tag
      value: local
  workspaces:
    - name: source
      volumeClaimTemplate:
        metadata:
          name: hookdrop-source
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
    
